### ISSUE TITLE
Ignores extra dim args

### ISSUE THREAD

**Issue by grahamas** [Tokazama/AxisIndices.jl#48]
The below should error, but doesn't.  It just constructs a 1D AxisArray with axis xs rather than both (xs, ys) specified (which wouldn't fit the provided data.
```
xs, ys = 0.0:10.0:300.0, 0.0:10.0:290.0
arr = AxisArray(xs, xs, ys)
```
In fact, even `AxisArray(xs, (xs,ys))` doesn't error.

**Comment by Tokazama** [comment]
The issue here is that I've intentionally allowed things like...

```julia
AxisArray(A, [:a, :b])
```
...where the axes are constructed by iterating over `axes(A)` and `args...` until all of the axes for `A` are made. This means if `args` is smaller than `axes(A)` then it's assumed it's an ordinary axis and if `args` is longer trailing arguments are never reached. 

I've been thinking of changing this by enforcing something like `AxisArray(A, [:a, :b], nothing)` so the dimensions have to match and you can leave axes blank out of order like `AxisArray(A, nothing, [:a, :b])`. This would make a single pass that checks all arguments a lot easier to manage.

Does `nothing` make sense as an argument replacement or is there something else you think makes more sense.

**Comment by grahamas** [comment]
Let me make sure I'm understanding:  is the problem that for `A=rand(2,5)` you can have all:
```
AxisArray(A) # 1
AxisArray(A, [:a,:b]) # 2
AxisArray(A, [:a,:b], 0:5) # 3
AxisArray(A, ([:a,:b], 0:5)) # 4
```
and you can't distinguish necessarily between 2 and 4?  My first though is to say axes can't be tuples, but if I didn't know that was the rule that might fail in a weird way, too. 

`nothing` seems like a good idea -- all the axes have to be iterable anyway.  The only time it might screw anyone up is if they were trying to set the axis `[nothing]`.  I don't think there's anything that doesn't have that problem, though, so it makes the most sense to me.

**Comment by Tokazama** [comment]
> The only time it might screw anyone up is if they were trying to set the axis `[nothing]`. 

I think even that extremely rare use case would work because `AxisArray(ones(1,2), [nothing], [:a, :b])` should still work.

**Comment by grahamas** [comment]
Oh yeah, for sure. I meant you wouldn't get an error if you accidentally typed `AxisArray(ones(1,2), [nothing], [:a, :b])`.  As you say, it's an extremely rare use case so I don't think it's worth worrying about.

**Comment by Tokazama** [comment]
The current master branch should address this now. I'm hoping to get a new release out soon (a couple days at the most for improving code coverage and catching any other bugs).
